Csp 14/feature/linting and ci
clevyr/scaffold pull request #32
Opened 2022-05-08 20:42 UTC by alkrauss48

This takes @DeQuasar's work and revamps it to fit our new style of dependencies, as well as a handful of other necessary changes.

This will now add PHP, JS, and Sass linting - all of which will be passing upon a scaffold. Only thing I haven't tested yet is the  github actions file.

@gabe565 I don't mind pushing a scaffold up to a private repo of mine to see if it tests/lints/builds as expected, but wanted to get your opinion before doing that.

It also adds back in the nova page builder plugin, since it works w/ laravel 9 now

2022-05-09 16:07 UTC, gabe565 requested changes
Looks good! Left some comments. Let me know what you think.

2022-05-09 16:07 UTC, gabe565 commented on cmd/laravel/cmd.go
> -	"os"
I think our IDE import sort settings aren't the same. Did you explicitly set yours to split framework packages up from github packages?

2022-05-09 16:07 UTC, gabe565 commented on internal/module/map.go
> +
Another IDE import sort issue

2022-05-09 16:07 UTC, gabe565 commented on internal/module/npm.go
> +	return iexec.NewBuilder("npm", "run", "lint:fix").Run()
Any reason to not do this in a `then.run` action? I'm trying to make the actual scaffold be less opinionated and have most of the business logic stored in config/templates

2022-05-09 16:07 UTC, gabe565 commented on templates/laravel-10-before-composer/.github/workflows/laravel.yml
> +          SLACK_WEBHOOK_URL: {{`${{ secrets.SLACK_WEBHOOK }}`}}
Please remove the build and deploy step. These will fail before a dev site has been created so they should be left off at first.

I also don't love that the templating required lots of literal strings here. This is fine to merge but I'll make another issue to see if there's a solution to that.

2022-05-16 13:18 UTC, alkrauss48 commented on internal/module/npm.go
> +	return iexec.NewBuilder("npm", "run", "lint:fix").Run()
I'll put this as a then on the `eslint` task, and if it works then I'll push up the change.

2022-05-16 13:46 UTC, alkrauss48 commented on internal/module/npm.go
> +	return iexec.NewBuilder("npm", "run", "lint:fix").Run()
This worked, and has now been updated

2022-05-16 16:25 UTC, gabe565 approved these changes

2022-05-16 17:36 UTC, merged